/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.activex.visual;

/**
 *
 * @author guilherme.csilva73
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCarro
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPaneAplicacaoMDI = new javax.swing.JDesktopPane();
        mnuBarTelaPrincipal = new javax.swing.JMenuBar();
        mnuArquivoTelaPrincipal = new javax.swing.JMenu();
        mnuCadastrarVeiculo = new javax.swing.JMenuItem();
        mnuPesquisaVeiculo = new javax.swing.JMenuItem();
        mnuCadastrarRevenda = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPaneAplicacaoMDILayout = new javax.swing.GroupLayout(dskPaneAplicacaoMDI);
        dskPaneAplicacaoMDI.setLayout(dskPaneAplicacaoMDILayout);
        dskPaneAplicacaoMDILayout.setHorizontalGroup(
            dskPaneAplicacaoMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        dskPaneAplicacaoMDILayout.setVerticalGroup(
            dskPaneAplicacaoMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        mnuArquivoTelaPrincipal.setText("Arquivo");

        mnuCadastrarVeiculo.setText("Cadastrar Veículo");
        mnuArquivoTelaPrincipal.add(mnuCadastrarVeiculo);

        mnuPesquisaVeiculo.setText("Pesquisar Veículo");
        mnuArquivoTelaPrincipal.add(mnuPesquisaVeiculo);

        mnuCadastrarRevenda.setText("Cadastrar Revenda");
        mnuArquivoTelaPrincipal.add(mnuCadastrarRevenda);

        mnuSair.setText("Sair");
        mnuArquivoTelaPrincipal.add(mnuSair);

        mnuBarTelaPrincipal.add(mnuArquivoTelaPrincipal);

        setJMenuBar(mnuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskPaneAplicacaoMDI)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskPaneAplicacaoMDI)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPaneAplicacaoMDI;
    private javax.swing.JMenu mnuArquivoTelaPrincipal;
    private javax.swing.JMenuBar mnuBarTelaPrincipal;
    private javax.swing.JMenuItem mnuCadastrarRevenda;
    private javax.swing.JMenuItem mnuCadastrarVeiculo;
    private javax.swing.JMenuItem mnuPesquisaVeiculo;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
