/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.activex.visual;

/**
 *
 * @author guilherme.csilva73
 */
public class TelaCadastroVeiculoMDI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroVeiculoMDI
     */
    public TelaCadastroVeiculoMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFabricante = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblKm = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radFlex = new javax.swing.JRadioButton();
        radGasolina = new javax.swing.JRadioButton();
        radDiesel = new javax.swing.JRadioButton();
        lblRevenda = new javax.swing.JLabel();

        lblFabricante.setText("Fabricante");

        lblModelo.setText("Modelo");

        lblAno.setText("Ano");

        lblCor.setText("Cor");

        lblKm.setText("Km");

        lblValor.setText("Valor");

        jLabel1.setText("Combustível:");

        radFlex.setText("jRadioButton1");
        radFlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFlexActionPerformed(evt);
            }
        });

        radGasolina.setText("jRadioButton1");

        radDiesel.setText("jRadioButton1");

        lblRevenda.setText("Revenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFabricante)
                            .addComponent(lblModelo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRevenda)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAno)
                                    .addComponent(lblValor))
                                .addGap(162, 162, 162)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCor)
                                        .addGap(132, 132, 132)
                                        .addComponent(lblKm))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(58, 58, 58)
                                        .addComponent(radFlex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radGasolina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radDiesel)))))
                        .addGap(0, 46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblFabricante)
                .addGap(34, 34, 34)
                .addComponent(lblModelo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(lblCor)
                    .addComponent(lblKm))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(jLabel1)
                    .addComponent(radFlex)
                    .addComponent(radGasolina)
                    .addComponent(radDiesel))
                .addGap(37, 37, 37)
                .addComponent(lblRevenda)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radFlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFlexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radFlexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblKm;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblRevenda;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton radDiesel;
    private javax.swing.JRadioButton radFlex;
    private javax.swing.JRadioButton radGasolina;
    // End of variables declaration//GEN-END:variables
}
